<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>OGToolz.Atlas.Extensions.DependencyInjection</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Atlas\Atlas.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
