<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Atlas.Benchmarks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Atlas\Atlas.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
</Project>
